/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formes.Main;

import entities.Client;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ClientService;
/**
 *
 * @author PC
 */
public class ClientForm3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientForm3
     */
    ClientService Cs;
    DefaultTableModel model1;
    public ClientForm3() {
        initComponents();
        this.setTitle("Gstion Reservation");
        Cs=new ClientService();
        model1=(DefaultTableModel) TableClient.getModel();
        load();
    }
    
    public void load()
{
    model1.setRowCount(0);
    for (Client c:Cs.findAll())
    {
        
        
        model1.addRow(new Object[]{
        
        c.getId(),
        c.getNom(),
        c.getPrenom(),
        c.getPhone(),
        c.getEmail()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NameClientTxt = new javax.swing.JTextField();
        PrenomClientTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EmailClientTxt = new javax.swing.JTextField();
        PhoneClientTxt = new javax.swing.JTextField();
        AddClientBtn = new javax.swing.JButton();
        UpdateClientBtn = new javax.swing.JButton();
        DeleteClientBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableClient = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel6.setText("Nom");

        jLabel7.setText("Prenom");

        PrenomClientTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomClientTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Email");

        jLabel5.setText("Telephone");

        AddClientBtn.setText("Ajouter");
        AddClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientBtnActionPerformed(evt);
            }
        });

        UpdateClientBtn.setText("Modifier");
        UpdateClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClientBtnActionPerformed(evt);
            }
        });

        DeleteClientBtn.setText("Supprimer");
        DeleteClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClientBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(AddClientBtn)
                        .addGap(47, 47, 47)
                        .addComponent(UpdateClientBtn)
                        .addGap(45, 45, 45)
                        .addComponent(DeleteClientBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameClientTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(PrenomClientTxt))
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EmailClientTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(PhoneClientTxt))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(PhoneClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(NameClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(EmailClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(PrenomClientTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddClientBtn)
                    .addComponent(UpdateClientBtn)
                    .addComponent(DeleteClientBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        TableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "nom", "prenom", "email", "telephone"
            }
        ));
        TableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableClient);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrenomClientTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomClientTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomClientTxtActionPerformed

    private void AddClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientBtnActionPerformed
        if(Cs.create(new  Client(NameClientTxt.getText(),PrenomClientTxt.getText(),EmailClientTxt.getText(),PhoneClientTxt.getText())))
        {
            JOptionPane.showMessageDialog(this, "Client bien ajouter");
        }
        load();
    }//GEN-LAST:event_AddClientBtnActionPerformed

    private void DeleteClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClientBtnActionPerformed
        int selectedRow = TableClient.getSelectedRow();
        int response = JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer ce client!");
        if (response == 0) {
            if (selectedRow != -1) {
                int clientId = Integer.parseInt(model1.getValueAt(selectedRow, 0).toString());
                Client deletedClient = new Client(
                        clientId,
                        NameClientTxt.getText(),
                        PrenomClientTxt.getText(),
                        PhoneClientTxt.getText(),
                        EmailClientTxt.getText()
                );
                if (Cs.delete(deletedClient)) {
                    JOptionPane.showMessageDialog(this, "Le client a été suprimme avec succès!");
                    load();
                } else {
                    JOptionPane.showMessageDialog(this, "Échec de la supression du client.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner un client à suprimmer.");
            }
        }
    }//GEN-LAST:event_DeleteClientBtnActionPerformed

    private void UpdateClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClientBtnActionPerformed
        int selectedRow = TableClient.getSelectedRow();
        if (selectedRow != -1) {
            int clientId = Integer.parseInt(model1.getValueAt(selectedRow, 0).toString());
            Client updatedClient = new Client(
                    clientId,
                    NameClientTxt.getText(),
                    PrenomClientTxt.getText(),
                    PhoneClientTxt.getText(),
                    EmailClientTxt.getText()
            );
            if (Cs.update(updatedClient)) {
                model1.setValueAt(updatedClient.getNom(), selectedRow, 1);
                model1.setValueAt(updatedClient.getPrenom(), selectedRow, 2);
                model1.setValueAt(updatedClient.getPhone(), selectedRow, 3);
                model1.setValueAt(updatedClient.getEmail(), selectedRow, 4);
                JOptionPane.showMessageDialog(this, "Le client a été mis à jour avec succès!");
            } else {
                JOptionPane.showMessageDialog(this, "Échec de la mise à jour du client.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un client à mettre à jour.");
        }
    }//GEN-LAST:event_UpdateClientBtnActionPerformed

    private void TableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClientMouseClicked
        // JOptionPane.showConfirmDialog(this, "voulez vous supprimer");
                 int selectedRow = TableClient.getSelectedRow();
        if (selectedRow != -1) {
            NameClientTxt.setText(model1.getValueAt(selectedRow, 1).toString());
            PrenomClientTxt.setText(model1.getValueAt(selectedRow, 2).toString());
            PhoneClientTxt.setText(model1.getValueAt(selectedRow, 3).toString());
            EmailClientTxt.setText(model1.getValueAt(selectedRow, 4).toString());
        }
    }//GEN-LAST:event_TableClientMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClientBtn;
    private javax.swing.JButton DeleteClientBtn;
    private javax.swing.JTextField EmailClientTxt;
    private javax.swing.JTextField NameClientTxt;
    private javax.swing.JTextField PhoneClientTxt;
    private javax.swing.JTextField PrenomClientTxt;
    private javax.swing.JTable TableClient;
    private javax.swing.JButton UpdateClientBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}